/* global pc */
var TicketPickupManager = pc.createScript("ticketPickupManager");
TicketPickupManager.attributes.add("networkManagerEntity", { type: "entity" });
TicketPickupManager.attributes.add("localPlayerEntity", { type: "entity" });
TicketPickupManager.attributes.add("ticketSpawnRoot", { type: "entity" });
TicketPickupManager.attributes.add("ticketTemplate", { type: "entity" });
TicketPickupManager.attributes.add("collectRadius", { type: "number", default: 2.2 });
TicketPickupManager.attributes.add("collectSfx", { type: "asset", assetType: "audio" });
TicketPickupManager.prototype.initialize = function () { this.networkClient=this.networkManagerEntity&&this.networkManagerEntity.script?this.networkManagerEntity.script.arcadeNetworkClient:null; this._ticketEntities={}; this._requested={}; this._fx=[]; this._spawnPositions=[]; this._hasSentSpawnConfig=false; if (!this.networkClient) console.warn("[Tickets] Missing ArcadeNetworkClient"); if (!this.ticketSpawnRoot) console.warn("[Tickets] Missing ticketSpawnRoot"); if (!this.ticketTemplate) console.warn("[Tickets] Missing ticketTemplate"); if (this.ticketTemplate) this.ticketTemplate.enabled=false; this._spawnPositions=this._collectSpawnPositions(); this._trySendSpawnConfig(); if (this.networkClient&&this.networkClient.onConnected) this.networkClient.onConnected(this._trySendSpawnConfig.bind(this)); if (this.networkClient&&this.networkClient.onTicketCollected) this.networkClient.onTicketCollected(this._onTicketCollected.bind(this)); };
TicketPickupManager.prototype.update = function (dt) { this._trySendSpawnConfig(); this._syncTickets(); this._checkCollects(); this._updateFx(dt); };
TicketPickupManager.prototype._collectSpawnPositions = function () { var out=[]; var kids=this.ticketSpawnRoot?this.ticketSpawnRoot.children:[]; for (var i=0;i<kids.length;i++){ if(kids[i]&&kids[i].enabled){ var p=kids[i].getPosition(); out.push({x:p.x,y:p.y,z:p.z}); } } console.log("[Tickets] Spawn config positions", out.length); return out; };
TicketPickupManager.prototype._trySendSpawnConfig = function () { if (this._hasSentSpawnConfig) return; var hasNetworkClient=!!this.networkClient; var hasRoom=!!(this.networkClient&&this.networkClient.room); var spawnCount=this._spawnPositions?this._spawnPositions.length:0; console.log("[Tickets] Spawn send check | networkClient:",hasNetworkClient,"| room:",hasRoom,"| positions:",spawnCount); if (!this.networkClient) return; if (spawnCount!==16) return; var sent=this.networkClient.sendTicketSpawnConfig?this.networkClient.sendTicketSpawnConfig(this._spawnPositions):false; if (sent){ this._hasSentSpawnConfig=true; console.log("[Tickets] Spawn config send success:",this._hasSentSpawnConfig); } else console.log("[Tickets] Waiting for room connection before sending spawn config"); };
TicketPickupManager.prototype._syncTickets = function () { if (!this.networkClient) return; var tickets=this.networkClient.getTicketsState?this.networkClient.getTicketsState():{}; console.log("[Tickets] Known tickets:",Object.keys(tickets).length); for (var id in tickets){ if (!Object.prototype.hasOwnProperty.call(tickets,id)) continue; var t=tickets[id]; var ent=this._ticketEntities[id]; if(!ent && this.ticketTemplate){ ent=this.ticketTemplate.clone(); ent.enabled=true; this.app.root.addChild(ent); this._ticketEntities[id]=ent; } if(!ent) continue; ent.setPosition(t.x,t.y,t.z); ent.enabled=t.active===true; }
};
TicketPickupManager.prototype._checkCollects = function () { var local=this.localPlayerEntity; if(!local||!this.networkClient||!this.networkClient.sendTicketCollectRequest) return; var lp=local.getPosition(); var tickets=this.networkClient.getTicketsState?this.networkClient.getTicketsState():{}; for (var id in tickets){ var t=tickets[id]; if(!t.active||this._requested[id]) continue; var dx=lp.x-t.x,dy=lp.y-t.y,dz=lp.z-t.z; if (Math.sqrt(dx*dx+dy*dy+dz*dz)<=this.collectRadius){ this._requested[id]=true; this.networkClient.sendTicketCollectRequest(id); } } };
TicketPickupManager.prototype._onTicketCollected = function (payload) { if(!payload||!payload.ticketId) return; delete this._requested[payload.ticketId]; if (this.collectSfx && this.entity.sound) { this.entity.sound.play(this.collectSfx.name); } this._spawnFx(payload.x,payload.y,payload.z); };
TicketPickupManager.prototype._spawnFx = function (x,y,z) { for (var i=0;i<8;i++){ var e=new pc.Entity("ticketFx"); e.addComponent("render",{type:"sphere"}); e.setLocalScale(0.12,0.12,0.12); e.setPosition(x,y+0.5,z); this.app.root.addChild(e); this._fx.push({e:e,v:new pc.Vec3((Math.random()-0.5)*2,Math.random()*2+1,(Math.random()-0.5)*2),life:0.8}); } };
TicketPickupManager.prototype._updateFx = function (dt) { for (var i=this._fx.length-1;i>=0;i--){ var f=this._fx[i]; f.life-=dt; f.e.translate(f.v.x*dt,f.v.y*dt,f.v.z*dt); var s=Math.max(0.01,f.life); f.e.setLocalScale(s,s,s); if(f.life<=0){ f.e.destroy(); this._fx.splice(i,1);} } };
